// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Fslog - F# Logging Framework Library")>]
[<assembly: GuidAttribute("7D77EDBF-1186-4C9C-BECB-A1F1D5305FF2")>]
[<assembly: AssemblyProductAttribute("Fslog - F# Logging Framework")>]
[<assembly: AssemblyVersionAttribute("2.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.3.0")>]
[<assembly: AssemblyFileVersionAttribute("2.3.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fslog - F# Logging Framework Library"
    let [<Literal>] Guid = "7D77EDBF-1186-4C9C-BECB-A1F1D5305FF2"
    let [<Literal>] AssemblyProduct = "Fslog - F# Logging Framework"
    let [<Literal>] AssemblyVersion = "2.3.0"
    let [<Literal>] AssemblyInformationalVersion = "2.3.0"
    let [<Literal>] AssemblyFileVersion = "2.3.0"
